services:
  - type: worker
    name: tiktok-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tiktok_premium_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7944519785:AAHhAwmPkc4avLZu7S3d9dtO8FgRW1RL39c
